version: '2'

services:
  app:
    image: magently/magento
    ports:
      - "${EXTERNAL_HTTP_PORT}80"
    links:
      - db
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=db
    extra_hosts:
      - "magento.localhost:127.0.0.1"

  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=secret

