version: '2'

services:
  app:
    image: registry.magently.com/magently/magento
    ports:
      - "${EXTERNAL_HTTP_PORT}80"
    links:
      - db
    volumes:
      - ./module:/module
      - ./:/app
    environment:
      - MODULE_PATH=/module
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=db
      - MAGENTO_ADMIN_EMAIL=admin@example.com

  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=secret